set(ManifestActivationPolicy "eager")
set(ManifestName "${MY_BUILD_NAME}")
set(ManifestIcon "")
set(ManifestVersion "${PROJECT_VERSION}")
set(ManifestDescription "")
set(ManifestVendor "")
set(ManifestDocURL "")
set(ManifestContactAddress "")
set(ManifestCategory "")
set(ManifestCopyright "")
set(ManifestLicense "")
set(ManifestSymbolicName "${MY_BUILD_NAME}")
set(winResourse )
set(manifest_headers_dep )
  