set(ManifestActivationPolicy "eager")
set(ManifestName "foo")
set(ManifestCategory "foo")
set(ManifestContactAddress "http://www.foo.org")
set(ManifestCopyright "foolib")
set(ManifestDescription "foolib")
set(ManifestDocURL "http://www.foo.org")
set(ManifestLicense "http://www.apache.org/licenses/LICENSE-2.0.html")
set(ManifestVendor "foo inc.")
set(ManifestVersion "1")
