set(ManifestActivationPolicy "eager")
set(ManifestName "test")
set(ManifestCategory "test")
set(ManifestContactAddress "test")
set(ManifestCopyright "my copyright")
set(ManifestDescription "Test of manisfests")
set(ManifestDocURL "_")
set(ManifestIcon "Resources/test.ico")
set(ManifestLicense "GNU")
set(ManifestVendor "jaqt")
set(ManifestVersion "1.0")
